version: 2.1
jobs:

  # Run tests.
  Test:
    docker:
      - image: ubuntu:24.04
    environment:
      DEBIAN_FRONTEND: noninteractive
      PIP_BREAK_SYSTEM_PACKAGES: 1
    working_directory: ~/repo
    steps:
      - run: apt update -y
      - run: apt install -y git ssh
      - checkout
      - run: apt install -y python3 python3-pip python3-gdal python3-numpy libspatialindex-dev
      - run: pip3 install -r requirements-base.txt
      - run: ./load-vest-excerpts.py
      - run: ./null-island-test.py
      - restore_cache:
          keys:
            - test-makefile-{{ checksum "Makefile" }}
      - run: make assembled-state-RI.parquet
      - save_cache:
          key: test-makefile-{{ checksum "Makefile" }}
          paths:
            - Census
            - memoized

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  Everything:
    jobs:
      - Test
