version: 2.1
jobs:

  # Run tests.
  Test:
    machine:
      image: ubuntu-2004:202111-02
    working_directory: ~/repo
    steps:
      - checkout
      - run: pyenv global 3.9.4
      - restore_cache:
          keys:
            - test-dependencies-py-{{ checksum "requirements.txt" }}
      - run: pip3 install -U pip
      - run: sudo add-apt-repository -y ppa:migurski/planscore2021
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y libgeos-3.9.0=3.9.0-1~focal0 libgdal-dev=3.2.1+dfsg-1~focal0 gdal-bin=3.2.1+dfsg-1~focal0 libspatialindex-dev
      - run: CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip3 install -r requirements.txt
      - save_cache:
          key: test-dependencies-py-{{ checksum "requirements.txt" }}
          paths:
            - /opt/circleci/.pyenv/versions/3.6.5
      - run: ./load-vest-excerpts.py
      - run: ./null-island-test.py
      - restore_cache:
          keys:
            - test-makefile-{{ checksum "Makefile" }}
      - run: make assembled-state-RI.parquet
      - save_cache:
          key: test-makefile-{{ checksum "Makefile" }}
          paths:
            - Census
            - memoized

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  Everything:
    jobs:
      - Test
